CLEARSCREEN.

LOCK THROTTLE TO 1.
LOCK STEERING TO UP + R(0,0,180).

WAIT UNTIL SHIP:ALTITUDE > 10000.
LOCK STEERING TO UP + R(0,0,180) + R(0,-60,0).

PRINT "Beginning gravity turn.".

WAIT UNTIL FALSE.